### ISSUE TITLE
[BUG] Weird bug with the spyder-console: AnnotRegion has been deleted

### ISSUE THREAD

**Issue by mscheltienne** [mne-tools/mne-qt-browser#134]
This bug is relatively similar to #82 
Basically, the annotations are not displayed and the following `RuntimeError` is raised in the console when scrolling:

```
Traceback (most recent call last):
  File "/Users/scheltie/Documents/git/mne-tools/mne-qt-browser/mne_qt_browser/_pg_figure.py", line 3612, in _xrange_changed
    self._update_annotations_xrange(xrange)
  File "/Users/scheltie/Documents/git/mne-tools/mne-qt-browser/mne_qt_browser/_pg_figure.py", line 3660, in _update_annotations_xrange
    self.mne.plt.removeItem(region)
  File "/Users/scheltie/Documents/pyvenv/mscheltienne/cardio-audio-sleep/lib/python3.9/site-packages/pyqtgraph/graphicsItems/PlotItem/PlotItem.py", line 625, in removeItem
    self.vb.removeItem(item)
  File "/Users/scheltie/Documents/pyvenv/mscheltienne/cardio-audio-sleep/lib/python3.9/site-packages/pyqtgraph/graphicsItems/ViewBox/ViewBox.py", line 428, in removeItem
    scene.removeItem(item)
  File "/Users/scheltie/Documents/pyvenv/mscheltienne/cardio-audio-sleep/lib/python3.9/site-packages/pyqtgraph/GraphicsScene/GraphicsScene.py", line 403, in removeItem
    ret = QtWidgets.QGraphicsScene.removeItem(self, item)
RuntimeError: wrapped C/C++ object of type AnnotRegion has been deleted
```

-----------

This bug does not occur from a Python or IPython console, only from the spyder-console. As Spyder is distributed alongside MNE in the installers, it might be a good idea to fix it.

-----------

How to reproduce. In a **fresh** spyder console:

```
import mne
fname = mne.datasets.sample.data_path() / 'MEG' / 'sample' / 'sample_audvis_filt-0-40_raw.fif'
raw = mne.io.read_raw_fif(fname, preload=True)
annotations = mne.Annotations([1, 10, 20, 30], [1, 2, 1, 2], ['a', 'b', 'a', 'b'])
raw.set_annotations(annotations)
raw.plot()
```

I insist on **fresh**, because if you re-plot after in the same console it now works. 

-----------

Demo:

https://user-images.githubusercontent.com/73893616/180460867-d7b8bfd2-80df-4f23-9b23-39653f60c96a.mov

-----------

System information:

macOS 11.6
MNE 1.1.dev0
MNE Qt Browser: 0.4.dev0
Spyder-kernels: 2.3.2
Spyder: 5.3.2

**Comment by mscheltienne** [comment]
Closing as the issue seems to be resolved, either by updates from MNE/MNE-Qt-Browser, or by update from Spyder/Spyder-kernels.
