### ISSUE TITLE
[BUG] ValueError: invalid literal for int() with base 16: 'rk'

### ISSUE THREAD

**Issue by mscheltienne** [mne-tools/mne-qt-browser#14]
Next one, same venv, I wanted to try the sample dataset with the terminal command `mne-qt-browser`.
This time, I'm getting this traceback:

```
Using pyopengl with version 3.1.5
C:\Users\Mathieu\Documents\pyvenv\neurotin\lib\site-packages\mne_qt_browser\_pg_figure.py:732: DeprecationWarning: Parsing of hex strings that do not start with '#' isdeprecated and support will be removed in 0.13
  color = mkColor(self.mne.ch_color_dict[ch_type])
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Mathieu\Documents\pyvenv\neurotin\Scripts\mne-qt-browser.exe\__main__.py", line 7, in <module>
  File "C:\Users\Mathieu\Documents\pyvenv\neurotin\lib\site-packages\mne_qt_browser\__main__.py", line 22, in main
    raw.plot(block=True)
  File "C:\Users\Mathieu\Documents\pyvenv\neurotin\lib\site-packages\mne\io\base.py", line 1528, in plot
    return plot_raw(self, events, duration, start, n_channels, bgcolor,
  File "<decorator-gen-174>", line 24, in plot_raw
  File "C:\Users\Mathieu\Documents\pyvenv\neurotin\lib\site-packages\mne\viz\raw.py", line 367, in plot_raw
    fig = _get_browser(**params)
  File "C:\Users\Mathieu\Documents\pyvenv\neurotin\lib\site-packages\mne\viz\_figure.py", line 613, in _get_browser
    browser = backend._init_browser(**kwargs)
  File "C:\Users\Mathieu\Documents\pyvenv\neurotin\lib\site-packages\mne_qt_browser\_pg_figure.py", line 3722, in _init_browser
    browser = PyQtGraphBrowser(**kwargs)
  File "C:\Users\Mathieu\Documents\pyvenv\neurotin\lib\site-packages\mne_qt_browser\_pg_figure.py", line 2184, in __init__
    overview_bar = OverviewBar(self)
  File "C:\Users\Mathieu\Documents\pyvenv\neurotin\lib\site-packages\mne_qt_browser\_pg_figure.py", line 497, in __init__
    self.set_background()
  File "C:\Users\Mathieu\Documents\pyvenv\neurotin\lib\site-packages\mne_qt_browser\_pg_figure.py", line 732, in set_background
    color = mkColor(self.mne.ch_color_dict[ch_type])
  File "C:\Users\Mathieu\Documents\pyvenv\neurotin\lib\site-packages\pyqtgraph\functions.py", line 289, in mkColor
    g = int(c[2:4], 16)
ValueError: invalid literal for int() with base 16: 'rk'
Traceback (most recent call last):
  File "C:\Users\Mathieu\Documents\pyvenv\neurotin\lib\site-packages\mne_qt_browser\_pg_figure.py", line 1995, in run
    self.sigs.loadProgress.emit(n + 1)
RuntimeError: wrapped C/C++ object of type LoadRunnerSignals has been deleted
```

On another hand, the same command is working in my venv with mne installed in dev mode from the GitHub repository.. Obviously, both venv differs in several ways. In the one failing, I have another library installed that uses `pyqtgraph` as a dependency, so it was not updated when I installed the browser. The working venv is running 0.12.3 and the failing venv is running 0.12.2.

**Comment by larsoner** [comment]
The min for mne-qt-browser is 0.12.3, can you open a PR to update https://github.com/mne-tools/mne-qt-browser/blob/main/setup.py ? I've already added this req to the [conda-forge recipe](https://github.com/conda-forge/staged-recipes/pull/16711/files#diff-d2635628b1a3872447bb0a38ef2d73786c7a265f5dfe5f6f14cf0948bb3742e5R28)

**Comment by larsoner** [comment]
I suspect this is a dup of https://github.com/mne-tools/mne-qt-browser/issues/13

**Comment by mscheltienne** [comment]
Ok, I didn't have time to check more yesterday; but that was my guess too. 
Updating to 0.12.3 fixes both issues. I will add the requirement to `setup.py`.
