### ISSUE TITLE
TypeError: setattr expected 3 arguments, got 2

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-qt-browser#21]
When running the following script using IPython (from within the VSCode editor), I cannot execute the final cell (containing the plotting call) twice. Instead, it throws an error (pasted below). Do you have any idea why?

```python
# %%
import mne

from config import get_sourcedata

# %%
# Load and prepare data
vhdr, tsv = get_sourcedata(2, "single")
raw = mne.io.read_raw_brainvision(vhdr, preload=True)

# Set the EOG and ECG channels to their type
raw.set_channel_types({"ECG": "ecg", "HEOG": "eog", "VEOG": "eog"})

# Set a standard montage for plotting later
montage = mne.channels.make_standard_montage("standard_1020")
raw.set_montage(montage)

# Temporarily remove existing annotations for faster interactive plotting
raw.set_annotations(None)

# %%

with mne.viz.use_browser_backend('pyqtgraph'):
    raw.plot(block=True)
```

```plain
Extracting parameters from /run/user/1000/gvfs/sftp:host=XXX,user=XXX/home/XXX/Projects/ARC-Studies/eeg_compression/ecomp_data/sourcedata/sub-02/sub-02_stream-single.vhdr...
Setting channel info structure...
Reading 0 ... 2117319  =      0.000 ...  2117.319 secs...
Using pyqtgraph as 2D backend.
Using pyopengl with version 3.1.5
Channels marked as bad: none
Traceback (most recent call last):
  File "01_raw_inspection.py", line 32, in <module>
    raw.plot(block=True)
  File "/home/stefanappelhoff/miniconda3/envs/ecomp_analysis/lib/python3.8/site-packages/mne/io/base.py", line 1528, in plot
    return plot_raw(self, events, duration, start, n_channels, bgcolor,
  File "<decorator-gen-174>", line 24, in plot_raw
  File "/home/stefanappelhoff/miniconda3/envs/ecomp_analysis/lib/python3.8/site-packages/mne/viz/raw.py", line 367, in plot_raw
    fig = _get_browser(**params)
  File "/home/stefanappelhoff/miniconda3/envs/ecomp_analysis/lib/python3.8/site-packages/mne/viz/_figure.py", line 613, in _get_browser
    browser = backend._init_browser(**kwargs)
  File "/home/stefanappelhoff/miniconda3/envs/ecomp_analysis/lib/python3.8/site-packages/mne_qt_browser/_pg_figure.py", line 3727, in _init_browser
    browser = PyQtGraphBrowser(**kwargs)
  File "/home/stefanappelhoff/miniconda3/envs/ecomp_analysis/lib/python3.8/site-packages/mne_qt_browser/_pg_figure.py", line 2065, in __init__
    setattr(self.mne, qvalue)
TypeError: setattr expected 3 arguments, got 2
```

**Comment by marsipu** [comment]
Thanks a lot @sappelhoff , that was a bug with the loading of settings which are stored in QSettings (stores all device-settings not going into MNE-Config).

**Comment by sappelhoff** [comment]
nice that you are working on a fix already :-) thanks.
