### ISSUE TITLE
Epochs Plot looking for non-existent annotations

### ISSUE THREAD

**Issue by sportnoah14** [mne-tools/mne-qt-browser#70]
Hi,

When I try to use this with an `Epochs` object, it returns an error because it's trying to get the annotations field from `Epochs` which doesn't exist. Here's the error:

```
Loading data for 21 events and 2001 original time points ...
Traceback (most recent call last):
  File "/Users/sportsnoah14/opt/miniconda3/envs/ieeg/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-96c8a116aab9>", line 6, in <module>
    group_by='original'
  File "/Users/sportsnoah14/opt/miniconda3/envs/ieeg/lib/python3.7/site-packages/mne/epochs.py", line 1143, in plot
    group_by=group_by)
  File "/Users/sportsnoah14/opt/miniconda3/envs/ieeg/lib/python3.7/site-packages/mne/viz/epochs.py", line 904, in plot_epochs
    fig = _get_browser(**params)
  File "/Users/sportsnoah14/opt/miniconda3/envs/ieeg/lib/python3.7/site-packages/mne/viz/_figure.py", line 613, in _get_browser
    browser = backend._init_browser(**kwargs)
  File "/Users/sportsnoah14/opt/miniconda3/envs/ieeg/lib/python3.7/site-packages/mne_qt_browser/_pg_figure.py", line 3852, in _init_browser
    browser = PyQtGraphBrowser(**kwargs)
  File "/Users/sportsnoah14/opt/miniconda3/envs/ieeg/lib/python3.7/site-packages/mne_qt_browser/_pg_figure.py", line 2201, in __init__
    self.mne.new_annotation_labels = self._get_annotation_labels()
  File "/Users/sportsnoah14/opt/miniconda3/envs/ieeg/lib/python3.7/site-packages/mne/viz/_figure.py", line 136, in _get_annotation_labels
    return sorted(set(self.mne.inst.annotations.description) |
AttributeError: 'Epochs' object has no attribute 'annotations'
```

I could be missing something and not passing in the arguments as I should.

**Comment by sportnoah14** [comment]
Sorry, I solved by downloading newest version. My mistake.
